### PR TITLE
Add fork icon for forked repos

### PR DESCRIPTION
**Pull request by anilsenay**
I added new icon and changed background color for forked repositories.

I do not wanted to add external icon so I searched the best fit icon on MaterialUI icons

### CODE REVIEW

**Comment by okandavut** [comment]
Thanks for your effort! It's a really good design improvement for Reposlib. Thanks!

**Review by okandavut — APPROVED** [review]
Looks good! :)

**Comment by okandavut** [comment]
@all-contributors please add anilsenay for code

**Comment by anilsenay** [comment]
> @all-contributors please add anilsenay for code

@anilsenay maybe?

**Comment by okandavut** [comment]
@all-contributors please add @anilsenay for code

**Comment by okandavut** [comment]
It's not working. But no problem i added  :)

**Pull request merged**
